<h3 class="alert alert-success">Usuarios</h3>
<br/>

<p> <a href="<?php echo $this->url('sonuser-admin',array('controller'=>'users','action'=>'new'));?>">Novo</a></p>

<table class="table table-striped">
    <tr class="success">
        <th>Id</th>
        <th>Nome</th>
        <th>Email</th>
        <th>Editar</th>
        <th>Deletar</th>
    </tr>

    <?php foreach ($this->data as $entity): ?>
        <tr>
            <td><?= $entity->getId() ?></td>
            <td><?= $entity->getNome() ?></td>
            <td><?= $entity->getEmail() ?></td>
            <td>
              <a href="<?php echo $this->url('sonuser-admin',array('controller' => 'users', 'action' => 'edit', 'id' => $entity->getId()));
    ?>">Editar</a></td>
            <td>
              <a href="<?php echo $this->url('sonuser-admin',array('controller' => 'users', 'action' => 'delete', 'id' => $entity->getId()));
    ?>">Excluit</a></td>
           
        </tr>
        
    <?php endforeach; ?>

</table>
