<h3>Novo usuario</h3>

<form method="POST" action="<?= $this->url('sonuser-admin', array('controller' => 'users', 'action' => 'new')) ?>">
    <div class="container">    
        <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">                    
            <div class="panel panel-info" >
                <div class="panel-heading">
                    <div class="panel-title">Novo Usuario</div>
                    <div style="float:right; font-size: 80%; position: relative; top:-10px"></div>
                </div>     
                <div style="padding-top:30px" class="panel-body" >
                    <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                    <form id="loginform" class="form-horizontal" role="form">
                        <div style="margin-bottom: 25px" class="input-group">
                            <span class="input-group-addon"><i >Nome</i></span>
                            <input id="login-username" type="text" class="form-control" name="nome" value="" placeholder="nome">                                        
                        </div>
                        <div style="margin-bottom: 25px" class="input-group">
                            <span class="input-group-addon"><i >Email</i></span>
                            <input id="login-username" type="text" class="form-control" name="email" value="" placeholder="email">                                        
                        </div>
                        <div style="margin-bottom: 25px" class="input-group">
                            <span class="input-group-addon"><i >Senha</i></span>
                            <input id="login-password" type="password" class="form-control" name="password" placeholder="password">
                        </div>
                        <div class="input-group">
                            <div class="checkbox">
                                <label>
                                    <input id="login-remember" type="checkbox" name="administrador" value="1"> Administrador
                                </label>
                            </div>
                        </div>
                        <div style="margin-top:10px" class="form-group">
                            <!-- Button -->
                            <div class="col-sm-12 controls">
                                <button id="btn-login" class="btn btn-success">Cadastrar</button>
                            </div>
                        </div>
                    </form>     
                </div>                     
            </div>  
        </div>
    </div>
</form>
