<h3 class="alert alert-success"><i class="fa fa-user"></i>&nbsp;Contatos</h3>
<br/>

<p> <a href="<?php echo $this->url('sonuser-admin',array('controller'=>'contatos','action'=>'new'));?>">Novo</a></p>

<table class="table table-striped">
    <tr class="success">
        <th>Id</th>
        <th>Nome</th>
        <th>Email</th>
        <th>Telefone</th>
        <th>Endereco</th>
        <th>Bairro</th>
        <th>Editar</th>
        <th>Deletar</th>
    </tr>

    <?php foreach ($this->data as $entity): ?>
        <tr>
            <td><?= $entity->getId() ?></td>
            <td><?= $entity->getNome() ?></td>
            <td><?= $entity->getEmail() ?></td>
            <td><?= $entity->getTelefone() ?></td>
            <td><?= $entity->getEndereco() ?></td>
            <td><?= $entity->getBairro() ?></td>
            
            
            <td>
                <a class="btn btn-info glyphicon glyphicon-list" href="<?php echo $this->url('sonuser-admin', array('controller' => 'contatos', 'action' => 'edit', 'id' => $entity->getId()));
    ?>">Editar</a></td>
            <td>
              <a  class="btn btn-danger  glyphicon glyphicon-trash" href="<?php echo $this->url('sonuser-admin',array('controller' => 'contatos', 'action' => 'delete', 'id' => $entity->getId()));
    ?>">Excluir</a></td>
           
           
        </tr>
        
    <?php endforeach; ?>

</table>
