    <div class="bs-docs-grid">
    <div class="row-fluid show-grid cabecalho-paginacao">
    <div class="span6"><a class="btn btn-primary" href="/produto/add" >Novo produto</a></div>
    </div>
    </div>
    <hr>
    <div class="well">
    <table class="table">
    <thead>
    <tr>
    <td style="width: 20px;">ID</td>
    <td style="width: 100px;">Foto</td>
    <td>Nome</td>
    <td style="width: 50px;">Opções</td>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($produtos as $produto) { ?>
    <tr>
    <td><?php echo $produto->produto_id?></td>
    <td>
    <?php $foto = json_decode($produto->produto_foto); ?>
    <img src="/conteudos/produtos/<?php echo $foto[0]?>" height="100" width="100" /></td>
    <td><?php echo $produto->produto_nome?></td>
    <td>
    <a href="/produto/fotos/<?php echo $produto->produto_id?>"><i class="icon-camera"></i></a>
    <a href="/produto/editar/<?php echo $produto->produto_id?>"><i class="icon-pencil"></i></a>
    <a id="id-deletar" href="#deletar" role="button" rel="12"><i class="icon-remove"></i></a>
    </td>
    </tr>
    <?php } ?>
    </tbody>
    </table>
    </div> 