<h3 class="alert alert-success"><i class="fa fa-user"></i>&nbsp;Categorias</h3>
<br/>

<table class="table table-striped">
    <tr class="success">
        <th>Id</th>
        <th>Nome</th>
      
        <th>Editar</th>
        <th>Deletar</th>
    </tr>

    <?php foreach ($this->data as $entity): ?>
        <tr>
            <td><?= $entity->getId() ?></td>
            <td><?= $entity->getNome() ?></td>
    
            <td>editar</td>
            <td>
              <a  class="btn btn-danger  glyphicon glyphicon-trash" href="<?php echo $this->url('sonuser-admin',array('controller' => 'categorias', 'action' => 'delete', 'id' => $entity->getId()));
    ?>">Excluir</a></td>
           
           
        </tr>
        
    <?php endforeach; ?>

</table>
